name: Testing

on:
  push:
    branches:
      - master
      - dev

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    env:
      AUTH_SECRET_KEY: ${{ secrets.AUTH_SECRET_KEY }}
      DB_HOST: ${{ secrets.DB_HOST }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install base dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-base.txt

    - name: Install dev dependencies
      run: |
        python -m pip install -r requirements-dev.txt

    - name: Set working directory to /tests
      run: cd tests

    - name: Run Tests
      run: |
        pip install pytest pytest-cov
        pytest . --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html
