name: Testing

on:
  push:
    branches:
      - master
      - dev

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    env:
      AUTH_SECRET_KEY: ${{ secrets.AUTH_SECRET_KEY }}
      TEST_DB_URI: ${{ secrets.TEST_DB_URI }}
      S3_API_ENDPOINT: ${{ vars.S3_API_ENDPOINT }}
      S3_IPFS_URL: ${{ vars.S3_IPFS_URL }}
      S3_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY_ID }}
      S3_SECRET_ACCESS_KEY_ID: ${{ secrets.S3_SECRET_ACCESS_KEY_ID }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11.3

    - name: Install base dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-base.txt

    - name: Install dev dependencies
      run: |
        python -m pip install -r requirements-dev.txt

    - name: Compile Translations
      uses: whtsky/msgfmt-action@20190305

    - name: Set working directory to /tests
      run: cd tests

    - name: Run Tests
      run: |
        pytest
