name: Testing

on:
  push:
    branches:
      - master
      - dev

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install base dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-base.txt

    - name: Install dev dependencies
      run: |
        python -m pip install -r requirements-dev.txt

    - name: Run Tests
      run: pytest tests
